# Generated by Django 3.0.14 on 2022-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='age',
            field=models.IntegerField(),
        ),
    ]
