# Generated by Django 4.1.3 on 2022-11-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221122_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='name',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='email',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='api',
            name='age',
        ),
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
